development:
  adapter: postgresql
  database: wish_list_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wish_list_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wish_list_production
  pool: 5
  timeout: 5000